/* eslint-disable @next/next/no-css-tags */
import { Toaster } from "react-hot-toast";
import "./globals.css";
import "boxicons/css/boxicons.min.css";
import Script from "next/script";

export const metadata = {
  title: "Course Files",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/theme/sneat-1.0.0/assets/css/demo.css" />
        <script src="/theme/sneat-1.0.0/assets/js/main.js" defer></script>
        {/* Core CSS */}
        <link rel="stylesheet" href="/theme/sneat-1.0.0/assets/vendor/css/core.css" />
        <link rel="stylesheet" href="/theme/sneat-1.0.0/assets/vendor/css/theme-default.css" />
        <link rel="stylesheet" href="/theme/sneat-1.0.0/assets/css/demo.css" />
        {/* Vendor CSS (if needed) */}
        <link rel="stylesheet" href="/theme/sneat-1.0.0/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
        <title>Course Files</title>
      </head>
      <body>
        <Toaster position="top-center" />
        {children}

        {/* theme related scripts */}
        <script src="/theme/sneat-1.0.0/assets/js/config.js"></script>
        <script src="/theme/sneat-1.0.0/assets/vendor/libs/jquery/jquery.js"></script>
        <script src="/theme/sneat-1.0.0/assets/vendor/libs/popper/popper.js"></script>
        <script src="/theme/sneat-1.0.0/assets/vendor/js/bootstrap.js"></script>
        <script src="/theme/sneat-1.0.0/assets/js/helpers.js"></script>
        <script src="/theme/sneat-1.0.0/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
        <script src="/theme/sneat-1.0.0/assets/vendor/js/menu.js"></script>
        <script src="/theme/sneat-1.0.0/assets/js/main.js"></script>
      </body>
    </html>
  );
}
